<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Number of tries
    |--------------------------------------------------------------------------
    |
    | The slug is a shortened URL combination of 5 chars, therefore there might
    | be collisions in the database. We will provide 5 tries
    | for generating unique slug and after that will
    | throw Validate exception
    |
    */

    'number_of_tries' => env('URL_SHORTENING_NUMBER_OF_TRIES', 5),

    /*
    |--------------------------------------------------------------------------
    | Url charset
    |--------------------------------------------------------------------------
    |
    | The slug will be generated by using only this charset, feel free to
    | change it
    |
    */

    'url_charset' => '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz',

    /*
    |--------------------------------------------------------------------------
    | Url length
    |--------------------------------------------------------------------------
    |
    | The length of the slug, the max is 255
    |
    */

    'url_length' => 5,

    /*
    |--------------------------------------------------------------------------
    | Base url
    |--------------------------------------------------------------------------
    |
    | The base url for urls shortened visual versions of slugs
    |
    */

    'base_url' => env('APP_URL', 'http://localhost') . '/urls',

    /*
    |--------------------------------------------------------------------------
    | Old threshold in days and visits threshold
    |--------------------------------------------------------------------------
    |
    | Initially, the assessment states that there should be a job that
    | will delete all urls which are not visited (0 views) for more than 30
    | days. Feel free to change these values
    |
    */

    'old_threshold_in_days' => 30,

    'visits_threshold' => 0,
];
